# 03 — Modeling

Regression and classification models for the Ames Housing dataset.  
Reads preprocessed data from `../data/processed/`.

**Scope:** Modeling and evaluation only. No preprocessing, feature engineering, or EDA.

**Prerequisite:** Run `02_preprocessing.ipynb` first to generate the processed CSVs.

## 1. Imports

In [32]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    mean_squared_error,
    roc_auc_score,
)
from statsmodels.stats.outliers_influence import variance_inflation_factor

## 2. Load Processed Data

In [33]:
train_model = pd.read_csv('../data/processed/train.csv')
val_model   = pd.read_csv('../data/processed/val.csv')
test_model  = pd.read_csv('../data/processed/test.csv')

print(f"Train:      {train_model.shape}")
print(f"Validation: {val_model.shape}")
print(f"Test:       {test_model.shape}")

Train:      (2051, 95)
Validation: (439, 95)
Test:       (440, 95)

---
# Part A — Regression Models

Target: `log_SalePrice` (log-transformed to address right skew).  
Evaluation: RMSE on log scale and original scale.

## Model 1 — Baseline (Overall Qual + Total_SF + House_Age)

In [34]:
model1 = smf.ols(
    'log_SalePrice ~ Q("Overall Qual") + Total_SF + House_Age',
    data=train_model
).fit()
print(model1.summary())

val_model['pred_model1'] = model1.predict(val_model)
rmse_model1 = np.sqrt(mean_squared_error(val_model['log_SalePrice'], val_model['pred_model1']))
print(f"\nModel 1 — RMSE (log scale): {rmse_model1:.4f}")

val_model['pred_model1_original'] = np.exp(val_model['pred_model1'])
rmse_model1_original = np.sqrt(mean_squared_error(val_model['SalePrice'], val_model['pred_model1_original']))
print(f"Model 1 — RMSE (original scale): ${rmse_model1_original:,.0f}")

                            OLS Regression Results
==============================================================================
Dep. Variable:          log_SalePrice   R-squared:                       0.808
Model:                            OLS   Adj. R-squared:                  0.807
Method:                 Least Squares   F-statistic:                     2864.
Date:                Fri, 17 Apr 2026   Prob (F-statistic):               0.00
Time:                        19:32:49   Log-Likelihood:                 631.55
No. Observations:                2051   AIC:                            -1255.
Df Residuals:                    2047   BIC:                            -1233.
Df Model:                           3
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept            10.8464      0.025    428.346      0.000      10.797      10.896
Q("Overall Qual")     0.1241      0.004     29.230      0.000       0.116       0.132
Total_SF              0.0002   6.26e-06     32.429      0.000       0.000       0.000
House_Age            -0.0027      0.000    -16.627      0.000      -0.003      -0.002
==============================================================================
Omnibus:                     1550.007   Durbin-Watson:                   1.977
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            92838.817
Skew:                          -2.995   Prob(JB):                         0.00
Kurtosis:                      35.411   Cond. No.                     1.75e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.75e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Model 1 — RMSE (log scale): 0.1916
Model 1 — RMSE (original scale): $29,529

## Model 2 — Multiple Numeric Predictors

In [35]:
formula_model2 = '''
log_SalePrice ~ Qual_Cond
                + np.log(Total_SF)
                + np.log(Q("Lot Area"))
                + np.log(Q("Garage Area") + 1)
                + Total_Bath
                + House_Age
                + Years_Since_Remod
'''

model2 = smf.ols(formula_model2, data=train_model).fit()
print(model2.summary())

val_model['pred_model2'] = model2.predict(val_model)
rmse_model2 = np.sqrt(mean_squared_error(val_model['log_SalePrice'], val_model['pred_model2']))
print(f"\nModel 2 — RMSE (log scale): {rmse_model2:.4f}")

val_model['pred_model2_original'] = np.exp(val_model['pred_model2'])
rmse_model2_original = np.sqrt(mean_squared_error(val_model['SalePrice'], val_model['pred_model2_original']))
print(f"Model 2 — RMSE (original scale): ${rmse_model2_original:,.0f}")

                            OLS Regression Results
==============================================================================
Dep. Variable:          log_SalePrice   R-squared:                       0.863
Model:                            OLS   Adj. R-squared:                  0.863
Method:                 Least Squares   F-statistic:                     1844.
Date:                Fri, 17 Apr 2026   Prob (F-statistic):               0.00
Time:                        19:32:49   Log-Likelihood:                 982.41
No. Observations:                2051   AIC:                            -1949.
Df Residuals:                    2043   BIC:                            -1904.
Df Model:                           7
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        6.5073      0.103     63.085      0.000       6.305       6.710
Qual_Cond                        0.0124      0.000     27.416      0.000       0.012       0.013
np.log(Total_SF)                 0.5353      0.015     35.077      0.000       0.505       0.565
np.log(Q("Lot Area"))            0.0914      0.007     12.753      0.000       0.077       0.105
np.log(Q("Garage Area") + 1)     0.0220      0.003      8.529      0.000       0.017       0.027
Total_Bath                       0.0555      0.006      9.800      0.000       0.044       0.067
House_Age                       -0.0037      0.000    -23.336      0.000      -0.004      -0.003
Years_Since_Remod               -0.0011      0.000     -4.588      0.000      -0.001      -0.001
==============================================================================
Omnibus:                      888.827   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            20044.169
Skew:                          -1.507   Prob(JB):                         0.00
Kurtosis:                      18.015   Cond. No.                     1.95e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.95e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

Model 2 — RMSE (log scale): 0.1628
Model 2 — RMSE (original scale): $26,656

In [36]:
# VIF — Model 2
X_model2 = pd.DataFrame({
    'Qual_Cond':    train_model['Qual_Cond'],
    'log_Total_SF':    np.log(train_model['Total_SF']),
    'log_Lot_Area':    np.log(train_model['Lot Area']),
    'log_Garage_Area': np.log(train_model['Garage Area'] + 1),
    'Total_Bath':      train_model['Total_Bath'],
    'House_Age':       train_model['House_Age'],
    'Years_Since_Remod': train_model['Years_Since_Remod']
}).dropna()

X_model2 = sm.add_constant(X_model2)

vif_model2 = pd.DataFrame({
    'variable': X_model2.columns,
    'VIF': [variance_inflation_factor(X_model2.values, i) for i in range(X_model2.shape[1])]
})
print("VIF — Model 2:")
vif_model2[vif_model2['variable'] != 'const'].sort_values('VIF', ascending=False)

VIF — Model 2:

            variable       VIF
2       log_Total_SF  2.147234
6          House_Age  2.098229
7  Years_Since_Remod  2.088388
5         Total_Bath  1.934484
1          Qual_Cond  1.541421
3       log_Lot_Area  1.265321
4    log_Garage_Area  1.233064

## Model 3 — Numeric + Categorical Predictors (Neighborhood_grouped)

In [37]:
formula_model3 = '''
log_SalePrice ~ Q("Overall Qual")
                + np.log(Total_SF)
                + np.log(Q("Lot Area"))
                + np.log(Q("Garage Area") + 1)
                + Total_Bath
                + House_Age
                + Years_Since_Remod
                + C(Neighborhood_grouped)
                + C(Q("Bldg Type"))
                + C(Q("Kitchen Qual"))
'''

model3 = smf.ols(formula_model3, data=train_model).fit()
print(model3.summary())

val_model['pred_model3'] = model3.predict(val_model)
rmse_model3 = np.sqrt(mean_squared_error(val_model['log_SalePrice'], val_model['pred_model3']))
print(f"\nModel 3 — RMSE (log scale): {rmse_model3:.4f}")

val_model['pred_model3_original'] = np.exp(val_model['pred_model3'])
rmse_model3_original = np.sqrt(mean_squared_error(val_model['SalePrice'], val_model['pred_model3_original']))
print(f"Model 3 — RMSE (original scale): ${rmse_model3_original:,.0f}")

                            OLS Regression Results
==============================================================================
Dep. Variable:          log_SalePrice   R-squared:                       0.875
Model:                            OLS   Adj. R-squared:                  0.874
Method:                 Least Squares   F-statistic:                     617.3
Date:                Fri, 17 Apr 2026   Prob (F-statistic):               0.00
Time:                        19:32:50   Log-Likelihood:                 1074.4
No. Observations:                2051   AIC:                            -2101.
Df Residuals:                    2027   BIC:                            -1966.
Df Model:                          23
Covariance Type:            nonrobust
======================================================================================================
                                         coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
Intercept                              7.4875      0.124     60.566      0.000       7.245       7.730
C(Neighborhood_grouped)[T.Edwards]    -0.0091      0.018     -0.512      0.609      -0.044       0.026
C(Neighborhood_grouped)[T.Gilbert]    -0.0086      0.017     -0.501      0.617      -0.042       0.025
C(Neighborhood_grouped)[T.NAmes]       0.0392      0.015      2.558      0.011       0.009       0.069
C(Neighborhood_grouped)[T.NridgHt]     0.1021      0.018      5.567      0.000       0.066       0.138
C(Neighborhood_grouped)[T.OldTown]    -0.0117      0.020     -0.601      0.548      -0.050       0.027
C(Neighborhood_grouped)[T.Other]       0.0494      0.013      3.756      0.000       0.024       0.075
C(Neighborhood_grouped)[T.Sawyer]      0.0320      0.019      1.728      0.084      -0.004       0.068
C(Neighborhood_grouped)[T.Somerst]     0.0542      0.017      3.159      0.002       0.021       0.088
C(Q("Bldg Type"))[T.2fmCon]           -0.0519      0.024     -2.166      0.030      -0.099      -0.005
C(Q("Bldg Type"))[T.Duplex]           -0.0977      0.019     -5.143      0.000      -0.135      -0.060
C(Q("Bldg Type"))[T.Twnhs]            -0.0673      0.023     -2.956      0.003      -0.112      -0.023
C(Q("Bldg Type"))[T.TwnhsE]           -0.0374      0.015     -2.468      0.014      -0.067      -0.008
C(Q("Kitchen Qual"))[T.Fa]            -0.1943      0.028     -7.053      0.000      -0.248      -0.140
C(Q("Kitchen Qual"))[T.Gd]            -0.0896      0.014     -6.279      0.000      -0.118      -0.062
C(Q("Kitchen Qual"))[T.Po]            -0.1798      0.146     -1.235      0.217      -0.465       0.106
C(Q("Kitchen Qual"))[T.TA]            -0.1163      0.017     -7.032      0.000      -0.149      -0.084
Q("Overall Qual")                      0.0868      0.004     21.420      0.000       0.079       0.095
np.log(Total_SF)                       0.4048      0.017     24.370      0.000       0.372       0.437
np.log(Q("Lot Area"))                  0.0835      0.010      8.527      0.000       0.064       0.103
np.log(Q("Garage Area") + 1)           0.0211      0.003      8.196      0.000       0.016       0.026
Total_Bath                             0.0630      0.006     11.061      0.000       0.052       0.074
House_Age                             -0.0014      0.000     -7.170      0.000      -0.002      -0.001
Years_Since_Remod                     -0.0019      0.000     -8.473      0.000      -0.002      -0.001
==============================================================================
Omnibus:                     1106.779   Durbin-Watson:                   1.945
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            27532.877
Skew:                          -2.023   Prob(JB):                         0.00
Kurtosis:                      20.487   Cond. No.                     2.56e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.56e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

Model 3 — RMSE (log scale): 0.1648
Model 3 — RMSE (original scale): $24,210

## Model 4 — Simplified Categorical Predictors

In [38]:
formula_model4 = '''
log_SalePrice ~ Q("Overall Qual")
                + np.log(Total_SF)
                + np.log(Q("Lot Area"))
                + np.log(Q("Garage Area") + 1)
                + Total_Bath
                + House_Age
                + Years_Since_Remod
                + C(Neighborhood_simple)
                + C(Kitchen_Qual_grouped)
                + C(Bldg_Type_simple)
'''

model4 = smf.ols(formula_model4, data=train_model).fit()
print(model4.summary())

val_model['pred_model4'] = model4.predict(val_model)
rmse_model4 = np.sqrt(mean_squared_error(val_model['log_SalePrice'], val_model['pred_model4']))
print(f"\nModel 4 — RMSE (log scale): {rmse_model4:.4f}")

val_model['pred_model4_original'] = np.exp(val_model['pred_model4'])
rmse_model4_original = np.sqrt(mean_squared_error(val_model['SalePrice'], val_model['pred_model4_original']))
print(f"Model 4 — RMSE (original scale): ${rmse_model4_original:,.0f}")

                            OLS Regression Results
==============================================================================
Dep. Variable:          log_SalePrice   R-squared:                       0.868
Model:                            OLS   Adj. R-squared:                  0.867
Method:                 Least Squares   F-statistic:                     1217.
Date:                Fri, 17 Apr 2026   Prob (F-statistic):               0.00
Time:                        19:32:50   Log-Likelihood:                 1016.8
No. Observations:                2051   AIC:                            -2010.
Df Residuals:                    2039   BIC:                            -1942.
Df Model:                          11
Covariance Type:            nonrobust
=====================================================================================================
                                        coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
Intercept                             7.3032      0.113     64.856      0.000       7.082       7.524
C(Neighborhood_simple)[T.Other]      -0.0606      0.012     -5.234      0.000      -0.083      -0.038
C(Kitchen_Qual_grouped)[T.Low]       -0.0983      0.024     -4.135      0.000      -0.145      -0.052
C(Kitchen_Qual_grouped)[T.Medium]    -0.0300      0.009     -3.247      0.001      -0.048      -0.012
C(Bldg_Type_simple)[T.Other]         -0.0524      0.011     -4.791      0.000      -0.074      -0.031
Q("Overall Qual")                     0.0956      0.004     24.065      0.000       0.088       0.103
np.log(Total_SF)                      0.4202      0.017     25.073      0.000       0.387       0.453
np.log(Q("Lot Area"))                 0.0848      0.009      9.964      0.000       0.068       0.102
np.log(Q("Garage Area") + 1)          0.0212      0.003      8.282      0.000       0.016       0.026
Total_Bath                            0.0613      0.006     10.726      0.000       0.050       0.073
House_Age                            -0.0014      0.000     -8.502      0.000      -0.002      -0.001
Years_Since_Remod                    -0.0017      0.000     -7.353      0.000      -0.002      -0.001
==============================================================================
Omnibus:                      980.272   Durbin-Watson:                   1.979
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            19689.989
Skew:                          -1.768   Prob(JB):                         0.00
Kurtosis:                      17.761   Cond. No.                     1.95e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.95e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

Model 4 — RMSE (log scale): 0.1701
Model 4 — RMSE (original scale): $26,007

In [39]:
# VIF — Model 4 (continuous features only)
X_model4 = pd.DataFrame({
    'Overall Qual':    train_model['Overall Qual'],
    'log_Total_SF':    np.log(train_model['Total_SF']),
    'log_Lot_Area':    np.log(train_model['Lot Area']),
    'log_Garage_Area': np.log(train_model['Garage Area'] + 1),
    'Total_Bath':      train_model['Total_Bath'],
    'House_Age':       train_model['House_Age'],
    'Years_Since_Remod': train_model['Years_Since_Remod']
}).dropna()

X_model4 = sm.add_constant(X_model4)

vif_model4 = pd.DataFrame({
    'variable': X_model4.columns,
    'VIF': [variance_inflation_factor(X_model4.values, i) for i in range(X_model4.shape[1])]
})
print("VIF — Model 4:")
vif_model4[vif_model4['variable'] != 'const'].sort_values('VIF', ascending=False)

VIF — Model 4:

            variable       VIF
1       Overall Qual  2.684269
2       log_Total_SF  2.636224
6          House_Age  2.115679
5         Total_Bath  1.935169
7  Years_Since_Remod  1.840253
3       log_Lot_Area  1.280385
4    log_Garage_Area  1.228256

## Model 5 — Interaction: Neighborhood × Total_SF

In [40]:
formula_model5 = '''
log_SalePrice ~ Q("Overall Qual")
                + np.log(Total_SF)
                + np.log(Q("Lot Area"))
                + np.log(Q("Garage Area") + 1)
                + Total_Bath
                + House_Age
                + Years_Since_Remod
                + C(Neighborhood_simple)
                + C(Kitchen_Qual_grouped)
                + C(Bldg_Type_simple)
                + C(Neighborhood_simple):np.log(Total_SF)
'''

model5 = smf.ols(formula_model5, data=train_model).fit()
print(model5.summary())

val_model['pred_model5'] = model5.predict(val_model)
rmse_model5 = np.sqrt(mean_squared_error(val_model['log_SalePrice'], val_model['pred_model5']))
print(f"\nModel 5 — RMSE (log scale): {rmse_model5:.4f}")

val_model['pred_model5_original'] = np.exp(val_model['pred_model5'])
rmse_model5_original = np.sqrt(mean_squared_error(val_model['SalePrice'], val_model['pred_model5_original']))
print(f"Model 5 — RMSE (original scale): ${rmse_model5_original:,.0f}")

                            OLS Regression Results
==============================================================================
Dep. Variable:          log_SalePrice   R-squared:                       0.870
Model:                            OLS   Adj. R-squared:                  0.870
Method:                 Least Squares   F-statistic:                     1139.
Date:                Fri, 17 Apr 2026   Prob (F-statistic):               0.00
Time:                        19:32:51   Log-Likelihood:                 1035.8
No. Observations:                2051   AIC:                            -2046.
Df Residuals:                    2038   BIC:                            -1973.
Df Model:                          12
Covariance Type:            nonrobust
====================================================================================================================
                                                       coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------
Intercept                                            5.4116      0.326     16.619      0.000       4.773       6.050
C(Neighborhood_simple)[T.Other]                      2.0079      0.335      5.999      0.000       1.352       2.664
C(Kitchen_Qual_grouped)[T.Low]                      -0.1071      0.024     -4.538      0.000      -0.153      -0.061
C(Kitchen_Qual_grouped)[T.Medium]                   -0.0349      0.009     -3.792      0.000      -0.053      -0.017
C(Bldg_Type_simple)[T.Other]                        -0.0429      0.011     -3.922      0.000      -0.064      -0.021
Q("Overall Qual")                                    0.0926      0.004     23.330      0.000       0.085       0.100
np.log(Total_SF)                                     0.6626      0.043     15.562      0.000       0.579       0.746
C(Neighborhood_simple)[T.Other]:np.log(Total_SF)    -0.2579      0.042     -6.184      0.000      -0.340      -0.176
np.log(Q("Lot Area"))                                0.0796      0.008      9.386      0.000       0.063       0.096
np.log(Q("Garage Area") + 1)                         0.0224      0.003      8.835      0.000       0.017       0.027
Total_Bath                                           0.0635      0.006     11.180      0.000       0.052       0.075
House_Age                                           -0.0014      0.000     -8.640      0.000      -0.002      -0.001
Years_Since_Remod                                   -0.0017      0.000     -7.616      0.000      -0.002      -0.001
==============================================================================
Omnibus:                      976.653   Durbin-Watson:                   1.976
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            19455.575
Skew:                          -1.762   Prob(JB):                         0.00
Kurtosis:                      17.671   Cond. No.                     8.07e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.07e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

Model 5 — RMSE (log scale): 0.1701
Model 5 — RMSE (original scale): $25,827

In [41]:
# VIF — Model 5 (full design matrix including categoricals and interaction)
X = model5.model.exog
feature_names = model5.model.exog_names

vif_model5 = pd.DataFrame({
    'variable': feature_names,
    'VIF': [variance_inflation_factor(X, i) for i in range(X.shape[1])]
})
print("VIF — Model 5:")
vif_model5[vif_model5['variable'] != 'Intercept'].sort_values('VIF', ascending=False)

VIF — Model 5:

                                            variable          VIF
1                    C(Neighborhood_simple)[T.Other]  1169.623745
7   C(Neighborhood_simple)[T.Other]:np.log(Total_SF)  1109.215736
6                                   np.log(Total_SF)    17.564145
5                                  Q("Overall Qual")     3.036688
11                                         House_Age     2.209867
12                                 Years_Since_Remod     2.148171
10                                        Total_Bath     2.039225
3                  C(Kitchen_Qual_grouped)[T.Medium]     2.019583
8                              np.log(Q("Lot Area"))     1.863484
4                       C(Bldg_Type_simple)[T.Other]     1.613305
2                     C(Kitchen_Qual_grouped)[T.Low]     1.266657
9                       np.log(Q("Garage Area") + 1)     1.257939

## Model 6 — Reduced Core Model

In [42]:
formula_model6 = '''
log_SalePrice ~ Q("Overall Qual")
                + np.log(Total_SF)
                + C(Neighborhood_simple)
                + C(Kitchen_Qual_grouped)
'''

model6 = smf.ols(formula_model6, data=train_model).fit()
print(model6.summary())

val_model['pred_model6'] = model6.predict(val_model)
rmse_model6 = np.sqrt(mean_squared_error(val_model['log_SalePrice'], val_model['pred_model6']))
print(f"\nModel 6 — RMSE (log scale): {rmse_model6:.4f}")

val_model['pred_model6_original'] = np.exp(val_model['pred_model6'])
rmse_model6_original = np.sqrt(mean_squared_error(val_model['SalePrice'], val_model['pred_model6_original']))
print(f"Model 6 — RMSE (original scale): ${rmse_model6_original:,.0f}")

                            OLS Regression Results
==============================================================================
Dep. Variable:          log_SalePrice   R-squared:                       0.818
Model:                            OLS   Adj. R-squared:                  0.817
Method:                 Least Squares   F-statistic:                     1833.
Date:                Fri, 17 Apr 2026   Prob (F-statistic):               0.00
Time:                        19:32:51   Log-Likelihood:                 686.27
No. Observations:                2051   AIC:                            -1361.
Df Residuals:                    2045   BIC:                            -1327.
Df Model:                           5
Covariance Type:            nonrobust
=====================================================================================================
                                        coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
Intercept                             6.8395      0.116     58.790      0.000       6.611       7.068
C(Neighborhood_simple)[T.Other]      -0.0623      0.013     -4.745      0.000      -0.088      -0.037
C(Kitchen_Qual_grouped)[T.Low]       -0.2011      0.027     -7.470      0.000      -0.254      -0.148
C(Kitchen_Qual_grouped)[T.Medium]    -0.0929      0.010     -9.455      0.000      -0.112      -0.074
Q("Overall Qual")                     0.1192      0.004     27.525      0.000       0.111       0.128
np.log(Total_SF)                      0.5855      0.016     35.852      0.000       0.554       0.618
==============================================================================
Omnibus:                      580.409   Durbin-Watson:                   2.049
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3930.548
Skew:                          -1.155   Prob(JB):                         0.00
Kurtosis:                       9.376   Cond. No.                         309.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Model 6 — RMSE (log scale): 0.1963
Model 6 — RMSE (original scale): $29,584

In [43]:
# VIF — Model 6 (continuous features only)
X_model6 = pd.DataFrame({
    'Overall_Qual': train_model['Overall Qual'],
    'log_Total_SF': np.log(train_model['Total_SF'])
}).dropna()

X_model6 = sm.add_constant(X_model6)

vif_model6 = pd.DataFrame({
    'variable': X_model6.columns,
    'VIF': [variance_inflation_factor(X_model6.values, i) for i in range(X_model6.shape[1])]
})
print("VIF — Model 6:")
vif_model6[vif_model6['variable'] != 'const'].sort_values('VIF', ascending=False)

VIF — Model 6:

       variable      VIF
2  log_Total_SF  1.82995
1  Overall_Qual  1.82995

In [44]:
# =========================================================
# Modelo 7: substituição de Overall Qual por Qual_Cond
# =========================================================

formula_model7 = '''
log_SalePrice ~ Qual_Cond
                + np.log(Total_SF)
                + np.log(Q("Lot Area"))
                + np.log(Q("Garage Area") + 1)
                + Total_Bath
                + House_Age
                + Years_Since_Remod
                + C(Neighborhood_simple)
                + C(Kitchen_Qual_grouped)
                + C(Bldg_Type_simple)
'''

model7 = smf.ols(formula_model7, data=train_model).fit()
print(model7.summary())

# --- Avaliação ---
val_model['pred_model7'] = model7.predict(val_model)

rmse_model7 = np.sqrt(mean_squared_error(
    val_model['log_SalePrice'],
    val_model['pred_model7']
))
print(f"Model 7 - RMSE (log scale): {rmse_model7:.4f}")

val_model['pred_model7_original'] = np.exp(val_model['pred_model7'])

rmse_model7_original = np.sqrt(mean_squared_error(
    val_model['SalePrice'],
    val_model['pred_model7_original']
))
print(f"Model 7 - RMSE (original scale): ${rmse_model7_original:,.0f}")

                            OLS Regression Results
==============================================================================
Dep. Variable:          log_SalePrice   R-squared:                       0.872
Model:                            OLS   Adj. R-squared:                  0.871
Method:                 Least Squares   F-statistic:                     1260.
Date:                Fri, 17 Apr 2026   Prob (F-statistic):               0.00
Time:                        19:32:52   Log-Likelihood:                 1047.6
No. Observations:                2051   AIC:                            -2071.
Df Residuals:                    2039   BIC:                            -2004.
Df Model:                          11
Covariance Type:            nonrobust
=====================================================================================================
                                        coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
Intercept                             6.8813      0.109     63.266      0.000       6.668       7.095
C(Neighborhood_simple)[T.Other]      -0.1034      0.011     -9.219      0.000      -0.125      -0.081
C(Kitchen_Qual_grouped)[T.Low]       -0.0910      0.023     -3.880      0.000      -0.137      -0.045
C(Kitchen_Qual_grouped)[T.Medium]    -0.0426      0.009     -4.740      0.000      -0.060      -0.025
C(Bldg_Type_simple)[T.Other]         -0.0401      0.011     -3.707      0.000      -0.061      -0.019
Qual_Cond                             0.0116      0.000     25.670      0.000       0.011       0.012
np.log(Total_SF)                      0.5091      0.015     33.662      0.000       0.479       0.539
np.log(Q("Lot Area"))                 0.0852      0.008     10.170      0.000       0.069       0.102
np.log(Q("Garage Area") + 1)          0.0201      0.003      7.969      0.000       0.015       0.025
Total_Bath                            0.0622      0.006     11.046      0.000       0.051       0.073
House_Age                            -0.0032      0.000    -20.296      0.000      -0.004      -0.003
Years_Since_Remod                    -0.0004      0.000     -1.672      0.095      -0.001    6.82e-05
==============================================================================
Omnibus:                      898.066   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            21047.120
Skew:                          -1.518   Prob(JB):                         0.00
Kurtosis:                      18.397   Cond. No.                     2.12e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.12e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
Model 7 - RMSE (log scale): 0.1614
Model 7 - RMSE (original scale): $26,031

## Regression Summary

In [45]:
regression_summary = pd.DataFrame([
    {'Model': 'Model 1', 'Description': 'Baseline (Qual + SF + Age)',           'RMSE_log': rmse_model1, 'RMSE_original': rmse_model1_original},
    {'Model': 'Model 2', 'Description': 'Numeric predictors',                   'RMSE_log': rmse_model2, 'RMSE_original': rmse_model2_original},
    {'Model': 'Model 3', 'Description': '+ Categorical (grouped neighborhood)', 'RMSE_log': rmse_model3, 'RMSE_original': rmse_model3_original},
    {'Model': 'Model 4', 'Description': '+ Simplified categoricals',            'RMSE_log': rmse_model4, 'RMSE_original': rmse_model4_original},
    {'Model': 'Model 5', 'Description': '+ Interaction Neighborhood x SF',      'RMSE_log': rmse_model5, 'RMSE_original': rmse_model5_original},
    {'Model': 'Model 6', 'Description': 'Reduced core model',                   'RMSE_log': rmse_model6, 'RMSE_original': rmse_model6_original},
    {'Model': 'Model 7', 'Description': 'Qual_Cond instead of Overall Qual',    'RMSE_log': rmse_model7, 'RMSE_original': rmse_model7_original},
])

regression_summary

     Model                           Description  RMSE_log  RMSE_original
0  Model 1            Baseline (Qual + SF + Age)  0.191594   29528.708378
1  Model 2                    Numeric predictors  0.162772   26655.853365
2  Model 3  + Categorical (grouped neighborhood)  0.164843   24209.609251
3  Model 4             + Simplified categoricals  0.170060   26006.760512
4  Model 5       + Interaction Neighborhood x SF  0.170082   25827.299230
5  Model 6                    Reduced core model  0.196269   29583.602664
6  Model 7     Qual_Cond instead of Overall Qual  0.161416   26031.042095

---
# Part B — Classification Models

Target: `is_high` (binary — top price tier vs rest).  
Evaluation: confusion matrix, classification report, ROC-AUC. Threshold: 0.4.

## Logit 1 — Baseline (Overall Qual + Total_SF)

In [46]:
formula_logit1 = 'is_high ~ Q("Overall Qual") + np.log(Total_SF)'

model_logit1 = smf.logit(formula_logit1, data=train_model).fit()
print(model_logit1.summary())

val_model['pred_prob_1']  = model_logit1.predict(val_model)
val_model['pred_class_1'] = (val_model['pred_prob_1'] >= 0.4).astype(int)

print("\nConfusion Matrix:")
print(confusion_matrix(val_model['is_high'], val_model['pred_class_1']))
print(classification_report(val_model['is_high'], val_model['pred_class_1']))
print(f"ROC-AUC: {roc_auc_score(val_model['is_high'], val_model['pred_prob_1']):.4f}")

Optimization terminated successfully.
         Current function value: 0.248732
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                is_high   No. Observations:                 2051
Model:                          Logit   Df Residuals:                     2048
Method:                           MLE   Df Model:                            2
Date:                Fri, 17 Apr 2026   Pseudo R-squ.:                  0.6076
Time:                        19:32:52   Log-Likelihood:                -510.15
converged:                       True   LL-Null:                       -1300.1
Covariance Type:            nonrobust   LLR p-value:                     0.000
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept           -74.4692      4.230    -17.605      0.000     -82.760     -66.178
Q("Overall Qual")     1.4445      0.093     15.459      0.000       1.261       1.628
np.log(Total_SF)      8.1722      0.519     15.753      0.000       7.155       9.189
=====================================================================================

Confusion Matrix:
[[283  17]
 [ 24 115]]
              precision    recall  f1-score   support

           0       0.92      0.94      0.93       300
           1       0.87      0.83      0.85       139

    accuracy                           0.91       439
   macro avg       0.90      0.89      0.89       439
weighted avg       0.91      0.91      0.91       439

ROC-AUC: 0.9607

## Logit 2 — Baseline + Neighborhood + Kitchen Qual

In [47]:
formula_logit2 = '''
is_high ~ Q("Overall Qual")
          + np.log(Total_SF)
          + C(Neighborhood_simple)
          + C(Kitchen_Qual_grouped)
'''

model_logit2 = smf.logit(formula_logit2, data=train_model).fit()
print(model_logit2.summary())

val_model['pred_prob_2']  = model_logit2.predict(val_model)
val_model['pred_class_2'] = (val_model['pred_prob_2'] >= 0.4).astype(int)

print("\nConfusion Matrix:")
print(confusion_matrix(val_model['is_high'], val_model['pred_class_2']))
print(classification_report(val_model['is_high'], val_model['pred_class_2']))
print(f"ROC-AUC: {roc_auc_score(val_model['is_high'], val_model['pred_prob_2']):.4f}")

Optimization terminated successfully.
         Current function value: 0.224823
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:                is_high   No. Observations:                 2051
Model:                          Logit   Df Residuals:                     2045
Method:                           MLE   Df Model:                            5
Date:                Fri, 17 Apr 2026   Pseudo R-squ.:                  0.6453
Time:                        19:32:53   Log-Likelihood:                -461.11
converged:                       True   LL-Null:                       -1300.1
Covariance Type:            nonrobust   LLR p-value:                     0.000
=====================================================================================================
                                        coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
Intercept                           -75.6781      4.511    -16.777      0.000     -84.519     -66.837
C(Neighborhood_simple)[T.Other]      -0.9074      0.261     -3.474      0.001      -1.419      -0.396
C(Kitchen_Qual_grouped)[T.Low]       -1.6913      1.166     -1.451      0.147      -3.976       0.594
C(Kitchen_Qual_grouped)[T.Medium]    -1.6369      0.201     -8.158      0.000      -2.030      -1.244
Q("Overall Qual")                     1.0009      0.103      9.761      0.000       0.800       1.202
np.log(Total_SF)                      8.8653      0.565     15.703      0.000       7.759       9.972
=====================================================================================================

Confusion Matrix:
[[279  21]
 [ 21 118]]
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       300
           1       0.85      0.85      0.85       139

    accuracy                           0.90       439
   macro avg       0.89      0.89      0.89       439
weighted avg       0.90      0.90      0.90       439

ROC-AUC: 0.9640

## Logit 3 — Extended Numeric + Categorical

In [48]:
formula_logit3 = '''
is_high ~ Q("Overall Qual")
          + np.log(Total_SF)
          + np.log(Q("Lot Area"))
          + np.log(Q("Garage Area") + 1)
          + Total_Bath
          + House_Age
          + Years_Since_Remod
          + C(Neighborhood_simple)
          + C(Kitchen_Qual_grouped)
'''

model_logit3 = smf.logit(formula_logit3, data=train_model).fit()
print(model_logit3.summary())

val_model['pred_prob_3']  = model_logit3.predict(val_model)
val_model['pred_class_3'] = (val_model['pred_prob_3'] >= 0.4).astype(int)

print("\nConfusion Matrix:")
print(confusion_matrix(val_model['is_high'], val_model['pred_class_3']))
print(classification_report(val_model['is_high'], val_model['pred_class_3']))
print(f"ROC-AUC: {roc_auc_score(val_model['is_high'], val_model['pred_prob_3']):.4f}")

Optimization terminated successfully.
         Current function value: 0.200842
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:                is_high   No. Observations:                 2051
Model:                          Logit   Df Residuals:                     2040
Method:                           MLE   Df Model:                           10
Date:                Fri, 17 Apr 2026   Pseudo R-squ.:                  0.6832
Time:                        19:32:53   Log-Likelihood:                -411.93
converged:                       True   LL-Null:                       -1300.1
Covariance Type:            nonrobust   LLR p-value:                     0.000
=====================================================================================================
                                        coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
Intercept                           -80.1633      5.023    -15.959      0.000     -90.008     -70.318
C(Neighborhood_simple)[T.Other]      -1.1332      0.305     -3.711      0.000      -1.732      -0.535
C(Kitchen_Qual_grouped)[T.Low]       -0.9331      1.458     -0.640      0.522      -3.791       1.925
C(Kitchen_Qual_grouped)[T.Medium]    -1.1741      0.241     -4.863      0.000      -1.647      -0.701
Q("Overall Qual")                     1.0019      0.119      8.399      0.000       0.768       1.236
np.log(Total_SF)                      7.4698      0.616     12.121      0.000       6.262       8.678
np.log(Q("Lot Area"))                 1.3526      0.217      6.229      0.000       0.927       1.778
np.log(Q("Garage Area") + 1)          0.3601      0.193      1.862      0.063      -0.019       0.739
Total_Bath                            0.5892      0.157      3.741      0.000       0.281       0.898
House_Age                            -0.0073      0.005     -1.592      0.111      -0.016       0.002
Years_Since_Remod                    -0.0185      0.008     -2.341      0.019      -0.034      -0.003
=====================================================================================================

Confusion Matrix:
[[287  13]
 [ 15 124]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.95       300
           1       0.91      0.89      0.90       139

    accuracy                           0.94       439
   macro avg       0.93      0.92      0.93       439
weighted avg       0.94      0.94      0.94       439

ROC-AUC: 0.9750

In [49]:
# Odds ratios — Logit 3
odds_ratios_3 = pd.DataFrame({
    'variable':   model_logit3.params.index,
    'coef':       model_logit3.params.values,
    'odds_ratio': np.exp(model_logit3.params.values)
})
print("Odds Ratios — Logit 3:")
odds_ratios_3

Odds Ratios — Logit 3:

                             variable       coef    odds_ratio
0                           Intercept -80.163285  1.532948e-35
1     C(Neighborhood_simple)[T.Other]  -1.133242  3.219878e-01
2      C(Kitchen_Qual_grouped)[T.Low]  -0.933068  3.933450e-01
3   C(Kitchen_Qual_grouped)[T.Medium]  -1.174145  3.090831e-01
4                   Q("Overall Qual")   1.001918  2.723500e+00
5                    np.log(Total_SF)   7.469833  1.754314e+03
6               np.log(Q("Lot Area"))   1.352607  3.867497e+00
7        np.log(Q("Garage Area") + 1)   0.360111  1.433488e+00
8                          Total_Bath   0.589171  1.802493e+00
9                           House_Age  -0.007293  9.927332e-01
10                  Years_Since_Remod  -0.018507  9.816631e-01

## Logit 4 — Parsimonious (removes weak predictors from Logit 3)

In [50]:
formula_logit4 = '''
is_high ~ Q("Overall Qual")
          + np.log(Total_SF)
          + np.log(Q("Lot Area"))
          + Total_Bath
          + House_Age
          + Years_Since_Remod
          + C(Neighborhood_simple)
          + C(Kitchen_Qual_grouped)
'''

model_logit4 = smf.logit(formula_logit4, data=train_model).fit()
print(model_logit4.summary())

val_model['pred_prob_4']  = model_logit4.predict(val_model)
val_model['pred_class_4'] = (val_model['pred_prob_4'] >= 0.4).astype(int)

print("\nConfusion Matrix:")
print(confusion_matrix(val_model['is_high'], val_model['pred_class_4']))
print(classification_report(val_model['is_high'], val_model['pred_class_4']))
print(f"ROC-AUC: {roc_auc_score(val_model['is_high'], val_model['pred_prob_4']):.4f}")

Optimization terminated successfully.
         Current function value: 0.202067
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:                is_high   No. Observations:                 2051
Model:                          Logit   Df Residuals:                     2041
Method:                           MLE   Df Model:                            9
Date:                Fri, 17 Apr 2026   Pseudo R-squ.:                  0.6812
Time:                        19:32:53   Log-Likelihood:                -414.44
converged:                       True   LL-Null:                       -1300.1
Covariance Type:            nonrobust   LLR p-value:                     0.000
=====================================================================================================
                                        coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
Intercept                           -79.7062      4.990    -15.974      0.000     -89.486     -69.926
C(Neighborhood_simple)[T.Other]      -1.1836      0.306     -3.867      0.000      -1.784      -0.584
C(Kitchen_Qual_grouped)[T.Low]       -1.0607      1.408     -0.754      0.451      -3.820       1.698
C(Kitchen_Qual_grouped)[T.Medium]    -1.1862      0.242     -4.904      0.000      -1.660      -0.712
Q("Overall Qual")                     1.0338      0.118      8.764      0.000       0.803       1.265
np.log(Total_SF)                      7.5991      0.615     12.359      0.000       6.394       8.804
np.log(Q("Lot Area"))                 1.4258      0.216      6.614      0.000       1.003       1.848
Total_Bath                            0.5701      0.150      3.789      0.000       0.275       0.865
House_Age                            -0.0092      0.004     -2.080      0.038      -0.018      -0.001
Years_Since_Remod                    -0.0180      0.008     -2.289      0.022      -0.033      -0.003
=====================================================================================================

Confusion Matrix:
[[285  15]
 [ 15 124]]
              precision    recall  f1-score   support

           0       0.95      0.95      0.95       300
           1       0.89      0.89      0.89       139

    accuracy                           0.93       439
   macro avg       0.92      0.92      0.92       439
weighted avg       0.93      0.93      0.93       439

ROC-AUC: 0.9751

In [51]:
# Odds ratios — Logit 4
odds_ratios_4 = pd.DataFrame({
    'variable':   model_logit4.params.index,
    'coef':       model_logit4.params.values,
    'odds_ratio': np.exp(model_logit4.params.values)
})
print("Odds Ratios — Logit 4:")
odds_ratios_4

Odds Ratios — Logit 4:

                            variable       coef    odds_ratio
0                          Intercept -79.706179  2.421288e-35
1    C(Neighborhood_simple)[T.Other]  -1.183623  3.061676e-01
2     C(Kitchen_Qual_grouped)[T.Low]  -1.060745  3.461980e-01
3  C(Kitchen_Qual_grouped)[T.Medium]  -1.186237  3.053682e-01
4                  Q("Overall Qual")   1.033825  2.811799e+00
5                   np.log(Total_SF)   7.599138  1.996475e+03
6              np.log(Q("Lot Area"))   1.425836  4.161337e+00
7                         Total_Bath   0.570108  1.768458e+00
8                          House_Age  -0.009171  9.908707e-01
9                  Years_Since_Remod  -0.017991  9.821695e-01

## Logit Final — Without Kitchen Qual

In [52]:
formula_logit_final = '''
is_high ~ Q("Overall Qual")
          + np.log(Total_SF)
          + np.log(Q("Lot Area"))
          + Total_Bath
          + House_Age
          + Years_Since_Remod
          + C(Neighborhood_simple)
'''

model_logit_final = smf.logit(formula_logit_final, data=train_model).fit()
print(model_logit_final.summary())

val_model['pred_prob_final']  = model_logit_final.predict(val_model)
val_model['pred_class_final'] = (val_model['pred_prob_final'] >= 0.4).astype(int)

print("\nConfusion Matrix:")
print(confusion_matrix(val_model['is_high'], val_model['pred_class_final']))
print(classification_report(val_model['is_high'], val_model['pred_class_final']))
print(f"ROC-AUC: {roc_auc_score(val_model['is_high'], val_model['pred_prob_final']):.4f}")

Optimization terminated successfully.
         Current function value: 0.208128
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:                is_high   No. Observations:                 2051
Model:                          Logit   Df Residuals:                     2043
Method:                           MLE   Df Model:                            7
Date:                Fri, 17 Apr 2026   Pseudo R-squ.:                  0.6717
Time:                        19:32:54   Log-Likelihood:                -426.87
converged:                       True   LL-Null:                       -1300.1
Covariance Type:            nonrobust   LLR p-value:                     0.000
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                         -79.8841      4.906    -16.283      0.000     -89.500     -70.269
C(Neighborhood_simple)[T.Other]    -1.2574      0.308     -4.083      0.000      -1.861      -0.654
Q("Overall Qual")                   1.1666      0.115     10.123      0.000       0.941       1.393
np.log(Total_SF)                    7.5048      0.602     12.473      0.000       6.325       8.684
np.log(Q("Lot Area"))               1.4345      0.214      6.689      0.000       1.014       1.855
Total_Bath                          0.5432      0.147      3.692      0.000       0.255       0.832
House_Age                          -0.0115      0.004     -2.637      0.008      -0.020      -0.003
Years_Since_Remod                  -0.0337      0.007     -4.722      0.000      -0.048      -0.020
===================================================================================================

Confusion Matrix:
[[282  18]
 [ 18 121]]
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       300
           1       0.87      0.87      0.87       139

    accuracy                           0.92       439
   macro avg       0.91      0.91      0.91       439
weighted avg       0.92      0.92      0.92       439

ROC-AUC: 0.9751

## Classification Summary

In [53]:
classification_summary = pd.DataFrame([
    {'Model': 'Logit 1', 'Description': 'Baseline (Qual + SF)',                        'ROC-AUC': roc_auc_score(val_model['is_high'], val_model['pred_prob_1'])},
    {'Model': 'Logit 2', 'Description': '+ Neighborhood + Kitchen Qual',               'ROC-AUC': roc_auc_score(val_model['is_high'], val_model['pred_prob_2'])},
    {'Model': 'Logit 3', 'Description': '+ Extended numerics + categoricals',          'ROC-AUC': roc_auc_score(val_model['is_high'], val_model['pred_prob_3'])},
    {'Model': 'Logit 4', 'Description': 'Parsimonious (removes weak from Logit 3)',   'ROC-AUC': roc_auc_score(val_model['is_high'], val_model['pred_prob_4'])},
    {'Model': 'Logit Final', 'Description': 'Without Kitchen Qual',                   'ROC-AUC': roc_auc_score(val_model['is_high'], val_model['pred_prob_final'])},
])

classification_summary

         Model                               Description   ROC-AUC
0      Logit 1                      Baseline (Qual + SF)  0.960671
1      Logit 2             + Neighborhood + Kitchen Qual  0.963993
2      Logit 3        + Extended numerics + categoricals  0.975012
3      Logit 4  Parsimonious (removes weak from Logit 3)  0.975060
4  Logit Final                      Without Kitchen Qual  0.975084

In [54]:
base_formula = '''
log_SalePrice ~  np.log(Total_SF)
                + np.log(Q("Lot Area"))
                + np.log(Q("Garage Area") + 1)
                + Total_Bath
                + House_Age
                + Years_Since_Remod
                + C(Neighborhood_grouped)
                + C(Q("Bldg Type"))
                + C(Q("Kitchen Qual"))
'''

In [55]:
candidate_features = [
    "Qual_Cond",
    "Has_Garage"
]

results = []

# --- baseline ---
model = smf.ols(base_formula, data=train_model).fit()

preds = model.predict(val_model)

rmse_log = np.sqrt(mean_squared_error(val_model['log_SalePrice'], preds))
rmse_original = np.sqrt(mean_squared_error(
    val_model['SalePrice'], np.exp(preds)
))

results.append({
    "Feature": "BASELINE",
    "RMSE_log": rmse_log,
    "RMSE_original": rmse_original
})


# --- testes ---
for feat in candidate_features:
    formula_test = base_formula + f" + {feat}"

    model = smf.ols(formula_test, data=train_model).fit()

    preds = model.predict(val_model)

    rmse_log = np.sqrt(mean_squared_error(val_model['log_SalePrice'], preds))
    rmse_original = np.sqrt(mean_squared_error(
        val_model['SalePrice'], np.exp(preds)
    ))

    results.append({
        "Feature": feat,
        "RMSE_log": rmse_log,
        "RMSE_original": rmse_original
    })

pd.DataFrame(results).sort_values("RMSE_original")

      Feature  RMSE_log  RMSE_original
1   Qual_Cond  0.155896   23579.116696
2  Has_Garage  0.185523   28448.518826
0    BASELINE  0.185624   28703.798071

In [56]:
test_model['pred_log'] = model4.predict(test_model)

# RMSE log
rmse_log_test = np.sqrt(mean_squared_error(
    test_model['log_SalePrice'],
    test_model['pred_log']
))

# RMSE original
test_model['pred_original'] = np.exp(test_model['pred_log'])

rmse_original_test = np.sqrt(mean_squared_error(
    test_model['SalePrice'],
    test_model['pred_original']
))

print(f"Test RMSE (log): {rmse_log_test:.4f}")
print(f"Test RMSE (original): ${rmse_original_test:,.0f}")

Test RMSE (log): 0.1546
Test RMSE (original): $29,476

In [57]:
test_model['pred_prob'] = model_logit_final.predict(test_model)

In [58]:
threshold = 0.4  # ou o que escolheste

test_model['pred_class'] = (test_model['pred_prob'] >= threshold).astype(int)

In [59]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

print(confusion_matrix(test_model['is_high'], test_model['pred_class']))

print(classification_report(test_model['is_high'], test_model['pred_class']))

roc = roc_auc_score(test_model['is_high'], test_model['pred_prob'])
print(f"ROC-AUC: {roc:.4f}")

[[264  22]
 [ 10 144]]
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       286
           1       0.87      0.94      0.90       154

    accuracy                           0.93       440
   macro avg       0.92      0.93      0.92       440
weighted avg       0.93      0.93      0.93       440

ROC-AUC: 0.9825